### ISSUE TITLE
Unable to delete folders created in a python virtual envirorment

### ISSUE THREAD

**Issue by algent-al** [EbonJaeger/budgie-trash-applet#8]
Steps to reproduce the issue:
```
mkdir Pyenv && cd Pyenv
virtualenv -p /usr/bin/python3.7 asttokens
cd asttokens
source bin/activate
pip install asttokens
deactivate
```
Then delete `asttokens` folder from file manager.
Click on Trash applet and select "Delete Item"
The item will not be deleted and the error is:
```
** (budgie-panel:46638): CRITICAL **: 18:24:18.461: ../src/utils.c:45: Error deleting item: Error removing file /home/algent/.local/share/Trash/files/Pyenv/asttokens/lib/python3.7/lib-dynload/_asyncio.cpython-37m-x86_64-linux-gnu.so: Permission denied
```

**Comment by EbonJaeger** [comment]
I never considered that it might be possible to have items owned by another user (or root) in the trash bin, which is what's happening here. Nice find!

I am working on a solution that involves using the `trash://` URI everywhere. So far I have the main trash bin working good, but external mounted ones are giving some trouble.
